import argparse
import json
import sys
import os

from .config import init_config
from .dispatcher import dispatch, dispatch_to
from .db import init_db, get_message, mark_processed, search_messages, get_popup_messages
from .preview import format_preview
from .subscribe import load_subscribes, add_subscribe, remove_subscribe, ensure_me_dir


TOOL_NAMES = [
    "msg_list.py", "msg_show.py", "msg_mark.py",
    "sub_list.py", "sub_add.py", "sub_remove.py",
    "gh_config.py",
]

_TOOL_MODULE_MAP = {
    "msg_list.py": "tool_list",
    "msg_show.py": "tool_show",
    "msg_mark.py": "tool_mark",
    "sub_list.py": "tool_sub_list",
    "sub_add.py": "tool_sub_add",
    "sub_remove.py": "tool_sub_remove",
    "gh_config.py": "tool_gh_config",
}


TEMPLATES_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "templates")


def _get_template_dir(template_name: str) -> str:
    """返回指定模板的目录路径。"""
    return os.path.join(TEMPLATES_DIR, template_name)


def _generate_tool_scripts(tools_dir: str, man_name: str) -> None:
    os.makedirs(tools_dir, exist_ok=True)
    for name in TOOL_NAMES:
        module = _TOOL_MODULE_MAP[name]
        path = os.path.join(tools_dir, name)
        script = f"""#!/usr/bin/env python3
# auto-generated by claude-man init
import sys, os
os.chdir({os.path.dirname(tools_dir)!r})
sys.argv = [sys.argv[0], "--man", {man_name!r}] + [a for a in sys.argv[1:] if not a.startswith("--db-path")]
from claude_man.{module} import main; main()
"""
        with open(path, "w") as f:
            f.write(script.lstrip("\n"))
        os.chmod(path, 0o755)


def _ensure_claude_settings(work_dir: str, tools_dir: str, template_name: str = "default") -> None:
    """从模板生成 .claude/settings.json 和 CLAUDE.md。"""
    claude_dir = os.path.join(work_dir, ".claude")
    os.makedirs(claude_dir, exist_ok=True)
    name = os.path.basename(work_dir)
    hooks_dir = os.path.join(claude_dir, "hooks")

    _apply_template("settings.json", claude_dir, name, tools_dir, hooks_dir, template_name, work_dir)
    _apply_template("CLAUDE.md", claude_dir, name, tools_dir, hooks_dir, template_name, work_dir)
    _ensure_hooks(hooks_dir, name, work_dir, template_name)
    _ensure_prompt_template(claude_dir, template_name)


def _apply_template(template_name: str, target_dir: str, name: str, tools_dir: str,
                     hooks_dir: str = "", template_set: str = "default", work_dir: str = "") -> None:
    import claude_man as _cm
    _src_dir = os.path.dirname(os.path.dirname(os.path.abspath(_cm.__file__)))
    # 找 site-packages 目录：取 yaml 或 rich 的父目录
    _site_pkgs = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for _mod_name in ("yaml", "rich"):
        try:
            _mod = __import__(_mod_name)
            _site_pkgs = os.path.dirname(os.path.dirname(os.path.abspath(_mod.__file__)))
            break
        except (ImportError, AttributeError):
            continue

    template_path = os.path.join(
        TEMPLATES_DIR, template_set, f"{template_name}.template",
    )
    target_path = os.path.join(target_dir, template_name)
    if os.path.exists(template_path):
        with open(template_path) as f:
            content = f.read()
        content = (content
                   .replace("{{NAME}}", name)
                   .replace("{{TOOLS_DIR}}", tools_dir)
                   .replace("{{HOOKS_DIR}}", hooks_dir)
                   .replace("{{WORK_DIR}}", work_dir or tools_dir.rstrip("/tools"))
                   .replace("{{SRC_DIR}}", _src_dir)
                   .replace("{{SITE_PACKAGES}}", _site_pkgs))
        with open(target_path, "w") as f:
            f.write(content)
        print(f"  {template_name}:  {target_path}")
    else:
        # 降级：内联生成
        if template_name == "settings.json":
            allow_rules = [
                f"Bash(python3 {tools_dir}/*)",
                "Bash(python3 --version)",
                "Bash(which python3)",
            ]
            settings = {"permissions": {"allow": allow_rules}}
            with open(target_path, "w") as f:
                json.dump(settings, f, indent=2)
        elif template_name == "CLAUDE.md":
            _write_fallback_claude_md(target_path, name, tools_dir)
        print(f"  {template_name}:  {target_path} (使用内建模板)")


def _ensure_hooks(hooks_dir: str, man_name: str, work_dir: str, template_set: str = "default") -> None:
    """从模板生成 hook 脚本。"""
    os.makedirs(hooks_dir, exist_ok=True)
    template_path = os.path.join(
        TEMPLATES_DIR, template_set, "hook_check_new.py.template",
    )
    target_path = os.path.join(hooks_dir, "check_new.py")
    if os.path.exists(template_path):
        with open(template_path) as f:
            content = f.read()
        content = (
            content
            .replace("{{MAN_NAME}}", man_name)
            .replace("{{WORK_DIR}}", work_dir)
            .replace("{{HOOKS_DIR}}", hooks_dir)
        )
        with open(target_path, "w") as f:
            f.write(content)
        os.chmod(target_path, 0o755)
        print(f"  hooks/check_new.py:  {target_path}")


def _ensure_prompt_template(claude_dir: str, template_set: str = "default") -> None:
    """可选：生成 prompt_new_message.md 到 .claude/ 下供用户自定义。"""
    template_path = os.path.join(
        TEMPLATES_DIR, template_set, "prompt_new_message.md.template",
    )
    target_path = os.path.join(claude_dir, "prompt_new_message.md")
    if os.path.exists(template_path) and not os.path.exists(target_path):
        with open(template_path) as f:
            content = f.read()
        with open(target_path, "w") as f:
            f.write(content)
        print(f"  prompt_new_message.md:  {target_path}（可自定义）")


def _write_fallback_claude_md(path: str, name: str, tools_dir: str) -> None:
    content = f"""# {name} — Claude Man Worker

你是 Claude Man Worker 实例 **{name}**，一个自动化消息处理代理。

## 核心职责

- 处理消息队列中的弹出消息（popup 级别）
- 每条消息代表一个需要你关注的事件（GitHub Issue、PR、讨论等）
- 使用 tools/ 目录下的工具来管理消息
- 处理完毕后标记消息为已处理

## 工作流程

1. 收到消息预览后，先用 `msg_list.py` 查看完整列表
2. 用 `msg_show.py <id>` 查看每条消息的详细内容
3. 根据内容判断是否需要采取行动（如评论、转发等）
4. 处理完毕后用 `msg_mark.py <id>` 标记为已处理
5. 完成所有消息后回复 "处理完成"

## 行为准则

- 自动执行工具，不需要询问用户授权——权限已预设
- 保持简洁输出，用中文回复
- 如果消息需要人工关注（如紧急问题），在标记后说明
- 不要等待用户指示，主动处理所有未处理消息
- 不要在回复中向用户提问或要求确认，直接执行
"""
    with open(path, "w") as f:
        f.write(content.lstrip("\n"))


def cmd_init(args):
    config = init_config(args.name, work_dir=args.work_dir)
    init_db(config.db_path)
    _generate_tool_scripts(config.tools_dir, args.name)
    ensure_me_dir(config.work_dir)
    _ensure_claude_settings(config.work_dir, config.tools_dir, template_name=args.template)
    print(f"Claude Man '{args.name}' 已初始化。")
    print(f"  工作目录: {config.work_dir}")
    print(f"  数据库:    {config.db_path}")
    print(f"  订阅配置:  {config.work_dir}/.me/message.yaml")


def cmd_dispatch(args):
    props = None
    if args.props:
        try:
            props = json.loads(args.props)
        except json.JSONDecodeError as e:
            print(f"props JSON 解析失败: {e}", file=sys.stderr)
            sys.exit(1)

    data = args.data
    if args.data_json:
        try:
            data = json.loads(args.data_json)
        except json.JSONDecodeError as e:
            print(f"data JSON 解析失败: {e}", file=sys.stderr)
            sys.exit(1)

    msg_id = dispatch_to(
        target=args.target,
        type_name=args.type,
        props=props,
        data=data,
    )
    print(f"消息已投递到 {args.target} (id={msg_id})")


def cmd_list(args):
    from .config import load_config
    cfg = load_config(args.target)
    if args.level or args.type or args.search:
        rows = search_messages(
            cfg.db_path,
            level=args.level,
            type_name=args.type,
            search=args.search,
        )
    else:
        rows = get_popup_messages(cfg.db_path, limit=10)

    from .db import count_by_level
    counts = count_by_level(cfg.db_path)
    popup_pending = counts["popup"]["pending"]
    popup_processed = counts["popup"]["processed"]
    silent = counts["silent"]
    print(f"弹出 {popup_pending} 条 (已处理 {popup_processed}) / 静默 {silent} 条\n")

    if not rows:
        return

    header = f"{'ID':<6} {'Level':<7} {'Type':<25} {'Preview':<45} {'Created'}"
    print(header)
    print("-" * len(header))
    for row in rows:
        max_len = 45
        preview = (row["data"][:max_len - 3] + "...") if len(row["data"]) > max_len else row["data"]
        print(f"{row['id']:<6} {row['level']:<7} {row['type_name']:<25} {preview:<45} {row['created_at']}")


def cmd_show(args):
    from .config import load_config
    cfg = load_config(args.target)
    row = get_message(cfg.db_path, args.id)
    if not row:
        print(f"消息 #{args.id} 不存在。")
        return

    import json as _json
    def _pretty(obj):
        if isinstance(obj, str):
            try:
                return _json.dumps(_json.loads(obj), ensure_ascii=False, indent=2)
            except (_json.JSONDecodeError, TypeError):
                return obj
        return _json.dumps(obj, ensure_ascii=False, indent=2)

    print(f"Message #{row['id']}")
    print("─" * 40)
    print(f"Type:   {row['type_name']}")
    print(f"Level:  {row['level']}")
    print(f"Status: {row['status']}")
    print(f"Created: {row['created_at']}")
    if row["processed_at"]:
        print(f"Processed: {row['processed_at']}")
    print()
    print("Props:")
    print(_pretty(row["props"]))
    print()
    print("Data:")
    print(_pretty(row["data"]))


def cmd_mark(args):
    from .config import load_config
    cfg = load_config(args.target)

    if args.all:
        from .db import mark_all_popup_processed
        count = mark_all_popup_processed(cfg.db_path)
        print(f"已标记 {count} 条弹出消息为已处理。")
    elif args.ids:
        count = mark_processed(cfg.db_path, args.ids)
        print(f"已标记 {count} 条消息为已处理。")
    else:
        print("请指定要标记的消息 ID，或使用 --all。", file=sys.stderr)
        sys.exit(1)


def cmd_preview(args):
    from .config import load_config
    cfg = load_config(args.target)
    from .db import count_by_level
    rows = get_popup_messages(cfg.db_path, limit=cfg.preview.max_messages_per_turn)
    counts = count_by_level(cfg.db_path)
    print(format_preview(
        rows,
        max_preview_length=cfg.preview.max_preview_length,
        total_popup_pending=counts["popup"]["pending"],
        total_silent=counts["silent"],
    ))


def cmd_sub_list(args):
    from .config import load_config
    cfg = load_config(args.target)
    rules = load_subscribes(cfg.work_dir)
    if not rules:
        print("没有订阅规则。")
        return
    print(f"共 {len(rules)} 条订阅规则:\n")
    for i, rule in enumerate(rules):
        props_str = ", ".join(f"{k}={v}" for k, v in rule.get("props", {}).items())
        print(f"[{i}] {rule['type']}  ({props_str})")


def cmd_sub_add(args):
    from .config import load_config
    import re
    props = {}
    for p in args.props:
        if "=" not in p:
            print(f"无效格式: {p}，应为 key=regex", file=sys.stderr)
            sys.exit(1)
        key, _, pattern = p.partition("=")
        try:
            re.compile(pattern)
        except re.error as e:
            print(f"无效正则 {pattern!r}: {e}", file=sys.stderr)
            sys.exit(1)
        props[key] = pattern
    cfg = load_config(args.target)
    add_subscribe(cfg.work_dir, args.type, props)
    props_str = ", ".join(f"{k}={v}" for k, v in props.items())
    print(f"已添加订阅: {args.type} ({props_str})")


def cmd_sub_remove(args):
    from .config import load_config
    from .db import exclude_pending_by_type
    cfg = load_config(args.target)
    rules = load_subscribes(cfg.work_dir)
    if args.index < 0 or args.index >= len(rules):
        print(f"序号 {args.index} 不存在，共 {len(rules)} 条规则", file=sys.stderr)
        sys.exit(1)

    removed_type = rules[args.index].get("type", "")
    removed = remove_subscribe(cfg.work_dir, args.index)
    if not removed:
        print("删除失败", file=sys.stderr)
        sys.exit(1)

    if removed_type:
        count = exclude_pending_by_type(cfg.db_path, removed_type)
        if count > 0:
            print(f"已排除 {count} 条 {removed_type} 类型的 pending 消息（降级为静默）")

    print(f"已删除订阅: {removed['type']}")


def cmd_github_add_repo(args):
    from .source_github import load_config as gh_load, save_config as gh_save
    ghcfg = gh_load()

    parts = args.repo.split("/")
    if len(parts) != 2:
        print("repo 格式应为 owner/name", file=sys.stderr)
        sys.exit(1)

    ghcfg.setdefault("repos", []).append({
        "owner": parts[0],
        "name": parts[1],
        "events": args.events,
    })
    gh_save(ghcfg)
    print(f"已添加仓库 {args.repo}（{len(args.events)} 个事件类型）")


def cmd_github_remove_repo(args):
    from .source_github import load_config as gh_load, save_config as gh_save
    ghcfg = gh_load()
    repos = ghcfg.get("repos", [])
    if args.index < 0 or args.index >= len(repos):
        print(f"序号 {args.index} 不存在，共 {len(repos)} 个仓库", file=sys.stderr)
        sys.exit(1)
    removed = repos.pop(args.index)
    gh_save(ghcfg)
    print(f"已移除仓库 {removed['owner']}/{removed['name']}")


def cmd_github_list(args):
    from .source_github import load_config as gh_load
    ghcfg = gh_load()
    repos = ghcfg.get("repos", [])
    if not repos:
        print("没有配置的仓库。")
        print("用: claude-man github add-repo <target> <owner/name>")
        return
    print(f"共 {len(repos)} 个仓库:\n")
    for i, repo in enumerate(repos):
        events = ", ".join(repo.get("events", []))
        print(f"[{i}] {repo['owner']}/{repo['name']}  ({events})")


def cmd_template_list(args):
    """列出可用的模板集。"""
    if not os.path.isdir(TEMPLATES_DIR):
        print("没有找到模板目录。")
        return
    names = sorted(
        d for d in os.listdir(TEMPLATES_DIR)
        if os.path.isdir(os.path.join(TEMPLATES_DIR, d))
    )
    if not names:
        print("没有找到模板。")
        return
    print(f"可用模板 ({len(names)}):\n")
    for name in names:
        files = os.listdir(os.path.join(TEMPLATES_DIR, name))
        print(f"  {name}  ({len(files)} 个文件)")


def main():
    parser = argparse.ArgumentParser(prog="claude-man", description="Claude Man 消息编排系统")
    sub = parser.add_subparsers(dest="command", required=True)

    # init
    p_init = sub.add_parser("init", help="初始化一个新的 Claude Man")
    p_init.add_argument("name", help="Claude Man 名称")
    p_init.add_argument("--work-dir", help="工作目录（默认 ~/.claude-man/<name>）")
    p_init.add_argument("--template", default="default",
                         help="模板名称（默认 default，对应 templates/<name>/ 目录）")
    p_init.set_defaults(func=cmd_init)

    # dispatch
    p_dispatch = sub.add_parser("dispatch", help="投递消息")
    p_dispatch.add_argument("--target", required=True, help="目标 Claude Man")
    p_dispatch.add_argument("--type", required=True, help="消息类型（如 wexin.group_message）")
    p_dispatch.add_argument("--props", help='JSON 格式的 props，如 \'{"group_name":"项目群"}\'')
    p_dispatch.add_argument("--data", help="消息文本内容（纯文本）")
    p_dispatch.add_argument("--data-json", help="消息内容（JSON 对象）")
    p_dispatch.set_defaults(func=cmd_dispatch)

    # list
    p_list = sub.add_parser("list", help="列出消息")
    p_list.add_argument("target", help="Claude Man 名称")
    p_list.add_argument("--level", choices=["popup", "silent"], help="按等级筛选")
    p_list.add_argument("--type", help="按类型筛选")
    p_list.add_argument("--search", help="按关键词搜索")
    p_list.set_defaults(func=cmd_list)

    # show
    p_show = sub.add_parser("show", help="查看消息全文")
    p_show.add_argument("target", help="Claude Man 名称")
    p_show.add_argument("id", type=int, help="消息 ID")
    p_show.set_defaults(func=cmd_show)

    # mark
    p_mark = sub.add_parser("mark", help="标记消息已处理")
    p_mark.add_argument("target", help="Claude Man 名称")
    p_mark.add_argument("ids", type=int, nargs="*", help="消息 ID")
    p_mark.add_argument("--all", action="store_true", help="标记所有弹出消息为已处理")
    p_mark.set_defaults(func=cmd_mark)

    # preview
    p_preview = sub.add_parser("preview", help="预览未处理消息")
    p_preview.add_argument("target", help="Claude Man 名称")
    p_preview.set_defaults(func=cmd_preview)

    # sub commands
    p_sub_list = sub.add_parser("sub-list", help="查看订阅规则")
    p_sub_list.add_argument("target", help="Claude Man 名称")
    p_sub_list.set_defaults(func=cmd_sub_list)

    p_sub_add = sub.add_parser("sub-add", help="添加订阅规则")
    p_sub_add.add_argument("target", help="Claude Man 名称")
    p_sub_add.add_argument("type", help="消息类型（如 wexin.group_message）")
    p_sub_add.add_argument("props", nargs="*", help="key=regex [key=regex ...]")
    p_sub_add.set_defaults(func=cmd_sub_add)

    p_sub_remove = sub.add_parser("sub-remove", help="删除订阅规则并排除 pending 消息")
    p_sub_remove.add_argument("target", help="Claude Man 名称")
    p_sub_remove.add_argument("index", type=int, help="规则序号（从 sub-list 查看）")
    p_sub_remove.set_defaults(func=cmd_sub_remove)

    # template
    p_tpl = sub.add_parser("template", help="管理模板")
    tpl_sub = p_tpl.add_subparsers(dest="template_command", required=True)

    p_tpl_ls = tpl_sub.add_parser("list", help="列出可用模板")
    p_tpl_ls.set_defaults(func=cmd_template_list)

    # github source
    p_gh = sub.add_parser("github", help="管理 GitHub 源配置")
    gh_sub = p_gh.add_subparsers(dest="github_command", required=True)

    p_gh_add = gh_sub.add_parser("add-repo", help="添加要轮询的仓库")
    p_gh_add.add_argument("target", help="Claude Man 名称")
    p_gh_add.add_argument("repo", help="owner/name")
    p_gh_add.add_argument("--events", nargs="*",
                          default=["issue.opened", "issue.comment", "pr.opened",
                                   "pr.comment", "discussion.created", "discussion.comment"],
                          help="事件类型列表，默认全部")
    p_gh_add.set_defaults(func=cmd_github_add_repo)

    p_gh_rm = gh_sub.add_parser("remove-repo", help="移除仓库")
    p_gh_rm.add_argument("target", help="Claude Man 名称")
    p_gh_rm.add_argument("index", type=int, help="仓库序号（从 github list 查看）")
    p_gh_rm.set_defaults(func=cmd_github_remove_repo)

    p_gh_ls = gh_sub.add_parser("list", help="列出已配置的仓库")
    p_gh_ls.add_argument("target", help="Claude Man 名称")
    p_gh_ls.set_defaults(func=cmd_github_list)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
